### ISSUE TITLE
KeyError: 'VolumetricConvolution_updateOutput'

### ISSUE THREAD

**Issue by ghost** [greydanus/excitationbp#9]
>>> import excitationbp as eb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/qinfeng/excitationbp/excitationbp/__init__.py", line 9, in <module>
    from .functions.eb_convNd import *
  File "/work/qinfeng/excitationbp/excitationbp/functions/eb_convNd.py", line 322, in <module>
    _bind_functions()
  File "/work/qinfeng/excitationbp/excitationbp/functions/eb_convNd.py", line 316, in _bind_functions
    'update_output': make_update_output(fns[name + '_updateOutput']),
KeyError: 'VolumetricConvolution_updateOutput'

Do you know how to solve the problem ,sir?

**Comment by pavanbnv** [comment]
Comment the lines
    #    'VolumetricConvolution',
        'VolumetricConvolutionMM',
        'SpatialDilatedConvolution',
        'VolumetricDilatedConvolution',
     #   'SpatialFullConvolution',
       # 'VolumetricFullConvolution',

from lines 306 in eb_convNd.py

**Comment by pavanbnv** [comment]
FYR

https://github.com/pytorch/pytorch/blob/fc8834df4b9c129fb40ea26641ac8aaeeb702428/aten/src/THCUNN/generic/THCUNN.h
The header does not contain the VolumetricConvolution
